#!/usr/bin/env bash
# wormsam2 installer for macOS / Linux.  Run:  bash install.sh
# Creates ./.venv with torch (+MPS on Apple Silicon, +CUDA on Linux with NVIDIA), SAM2 and the wormsam2 tool,
# downloads the model on first selftest (~180 MB), and leaves a launcher at bin/wormsam2 (symlinked into ~/.local/bin).
set -euo pipefail
cd "$(dirname "$0")"
if ! command -v uv >/dev/null 2>&1; then
  echo ">> installing uv (python package manager)…"
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
fi
echo ">> creating virtual environment (.venv, Python 3.11)…"
uv venv --python 3.11 .venv --allow-existing
PY=.venv/bin/python
echo ">> installing torch…"
if [ "$(uname -s)" = "Linux" ] && command -v nvidia-smi >/dev/null 2>&1; then
  uv pip install --python $PY torch torchvision --index-url https://download.pytorch.org/whl/cu124
elif [ "$(uname -s)" = "Linux" ]; then
  uv pip install --python $PY torch torchvision --index-url https://download.pytorch.org/whl/cpu
else
  uv pip install --python $PY torch torchvision
fi
echo ">> installing SAM2 and wormsam2…"
uv pip install --python $PY -e .
mkdir -p bin
ROOT="$(pwd)"
cat > bin/wormsam2 <<EOL
#!/usr/bin/env bash
# launcher generated by install.sh; the install dir is hard-coded so the symlink in ~/.local/bin works
export PYTORCH_ENABLE_MPS_FALLBACK=1
exec "$ROOT/.venv/bin/wormsam2" "\$@"
EOL
chmod +x bin/wormsam2
mkdir -p "$HOME/.local/bin"
ln -sf "$(pwd)/bin/wormsam2" "$HOME/.local/bin/wormsam2"
echo ">> self-test (downloads the SAM2 model on first run)…"
bin/wormsam2 selftest
echo
if command -v wormsam2 >/dev/null 2>&1; then
  echo "Done. Usage:  wormsam2 run episodes_<video>.zip"
else
  echo "Done. The launcher is ~/.local/bin/wormsam2; add ~/.local/bin to PATH to call it as 'wormsam2'"
  echo "(e.g. echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.zshrc), or use the full path:"
  echo "  $(pwd)/bin/wormsam2 run episodes_<video>.zip"
fi
